Update examples-from-user-filed-issues.md: = vs. == bug.
Classic `=` used in conditional where comparison `==` was intended.

I tried the example and ran into:
```
SyntaxError: cannot assign to attribute here. Maybe you meant '==' instead of '='?
```

This fixes that.